/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module display_encoder_9 (
    input [15:0] state,
    output reg [47:0] out
  );
  
  
  
  always @* begin
    out[0+0+2-:3] = {2'h3{state[0+0-:1]}};
    out[0+3+2-:3] = {2'h3{state[1+0-:1]}};
    out[0+6+2-:3] = {2'h3{state[2+0-:1]}};
    out[0+9+2-:3] = {2'h3{state[3+0-:1]}};
    out[12+0+2-:3] = {2'h3{state[4+0-:1]}};
    out[12+3+2-:3] = {2'h3{state[5+0-:1]}};
    out[12+6+2-:3] = {2'h3{state[6+0-:1]}};
    out[12+9+2-:3] = {2'h3{state[7+0-:1]}};
    out[24+0+2-:3] = {2'h3{state[8+0-:1]}};
    out[24+3+2-:3] = {2'h3{state[9+0-:1]}};
    out[24+6+2-:3] = {2'h3{state[10+0-:1]}};
    out[24+9+2-:3] = {2'h3{state[11+0-:1]}};
    out[36+0+2-:3] = {2'h3{state[12+0-:1]}};
    out[36+3+2-:3] = {2'h3{state[13+0-:1]}};
    out[36+6+2-:3] = {2'h3{state[14+0-:1]}};
    out[36+9+2-:3] = {2'h3{state[15+0-:1]}};
  end
endmodule
