/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module initial_board_states_1 (
    input clk,
    input rst,
    input update_state,
    output reg [15:0] out
  );
  
  
  
  localparam BOARD_STATES = 64'hb08ef969b1204bef;
  
  reg [1:0] M_counter_d, M_counter_q = 1'h0;
  
  always @* begin
    M_counter_d = M_counter_q;
    
    out = 16'h0000;
    if (update_state) begin
      if (M_counter_q == 2'h3) begin
        out = BOARD_STATES[(M_counter_q)*16+15-:16];
        M_counter_d = 2'h0;
      end else begin
        out = BOARD_STATES[(M_counter_q)*16+15-:16];
        M_counter_d = M_counter_q + 1'h1;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
endmodule
