/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module win_checker_8 (
    input [15:0] state,
    output reg out
  );
  
  
  
  always @* begin
    out = (&state);
  end
endmodule
